### ISSUE TITLE
Errors on performance testing

### ISSUE THREAD

**Issue by Rubatharisan** [Morning-Train/Mail-notifications-for-Trello#1]
{ [Error: getaddrinfo ENOTFOUND smtp.mandrillapp.com]
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'smtp.mandrillapp.com' }

Error: getaddrinfo ENOTFOUND api.trello.com
    at errnoException (dns.js:44:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete](dns.js:94:26)

**Comment by Rubatharisan** [comment]
Seems like error got fixed by using Google DNS:
8.8.8.8
8.8.4.4
